s3-operations

diff --git a/s3/bash_script/sync b/s3/bash_script/sync
--- a/s3/bash_script/sync
+++ b/s3/bash_script/sync
@@ -1,1 +1,44 @@
 #!/usr/bin/env bash
+echo "s3 sync" 
+# exit immediately if a command exits with a non-zero status
+set -e
+
+#check the bucket name is provided
+if [ -z "$1" ]; then
+    echo "no first argument provided>"
+    exit 1
+fi
+
+#check the filename prefix is provided
+if [ -z "$2" ]; then
+    echo "no first argument provided>"
+    exit 1
+fi
+bucket_name=$1
+filename_prefix=$2
+
+#where we will store the files
+OUTPUT_DIR="/tmp/s3_bash_script/"
+
+#remove folder if it exists
+rm -r $OUTPUT_DIR
+
+#let create a output folder
+mkdir -p $OUTPUT_DIR
+
+# Generate a random number between 5 and 10
+num_files=$((RANDOM % 6 + 5))
+
+# Loop to create the random files
+for ((i = 1; i <= num_files; i++)); do
+  # Generate a random filename
+  filename="$OUTPUT_DIR/${filename_prefix}_$i.txt"
+
+  # Generate a random data and write it to the file
+  dd if=/dev/urandom of="$filename" bs=1024 count=1024
+  
+done
+
+  tree $OUTPUT_DIR
+
+aws s3 sync $OUTPUT_DIR s3://$bucket_name/files
